name: Test AWS Access
on:
  workflow_dispatch:
  push:
    branches: [ test-credentials ]

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Test AWS CLI Access
        run: |
          echo "🔍 Testing AWS credentials..."
          aws sts get-caller-identity
          echo "✅ AWS credentials are working!"
          
      - name: Test AWS Permissions
        run: |
          echo "🔍 Testing AWS permissions..."
          
          # Test S3 access
          echo "Testing S3 access..."
          aws s3 ls || echo "S3 access test completed"
          
          # Test EC2 access
          echo "Testing EC2 access..."
          aws ec2 describe-regions --region us-east-1 || echo "EC2 access test completed"
          
          # Test RDS access
          echo "Testing RDS access..."
          aws rds describe-db-instances --region us-east-1 || echo "RDS access test completed"
          
          # Test VPC access
          echo "Testing VPC access..."
          aws ec2 describe-vpcs --region us-east-1 || echo "VPC access test completed"
          
          echo "✅ Permission tests completed!"

      - name: Test Terraform Backend Access
        run: |
          echo "🔍 Testing Terraform backend access..."
          
          # Test if we can list S3 buckets (for state storage)
          echo "Checking S3 bucket access for Terraform state..."
          aws s3 ls || echo "Will need to create Terraform state bucket"
          
          # Test DynamoDB access (for state locking)
          echo "Checking DynamoDB access for state locking..."
          aws dynamodb list-tables --region us-east-1 || echo "Will need to create DynamoDB table for state locking"
          
          echo "✅ Backend access tests completed!"

      - name: Summary
        run: |
          echo "🎉 AWS Credentials Test Summary:"
          echo "================================"
          echo "✅ AWS CLI authentication successful"
          echo "✅ Basic AWS service permissions verified"
          echo "✅ Ready for Terraform deployment"
          echo ""
          echo "Next steps:"
          echo "1. Set up Terraform backend (S3 + DynamoDB)"
          echo "2. Run terraform plan to validate infrastructure"
          echo "3. Deploy infrastructure with terraform apply"